# Start from the deno image
FROM lynsei/bin:latest AS assets

FROM alpine:3.20 AS builder

# Install the GitHub CLI (gh)
RUN apk add \
        --no-cache \
        gzip bash github-cli

# Set working directory
WORKDIR /app
COPY scripts .
COPY src .
COPY deno.json .
COPY release-notes.md .
COPY --from=assets /app/release.tar /app/release.tar

ENTRYPOINT [ "bash", "/app/release.sh" ]
